from django.urls import path
from .views import (index,
                    cars,
                    car,
                    search,
                    register,
                    profile,
                    OrderListView,
                    OrderDetailView,
                    UserOrderListView,
                    OrderCreateView,
                    OrderUpdateView,
                    OrderDeleteView,
                    OrderLineCreateView,
                    OrderLineUpdateView,
                    OrderLineDeleteView)

urlpatterns = [
    path("", index, name="index"),
    path("cars/", cars, name="cars"),
    path("cars/<int:car_id>", car, name="car"),
    path("search/", search, name="search"),
    path("user_orders/", UserOrderListView.as_view(), name="user_orders"),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path("orders/", OrderListView.as_view(), name="orders"),
    path("orders/<int:pk>", OrderDetailView.as_view(), name="order"),
    path("orders/new", OrderCreateView.as_view(), name="orders_new"),
    path("orders/<int:pk>/update", OrderUpdateView.as_view(), name="orders_update"),
    path("orders/<int:pk>/delete", OrderDeleteView.as_view(), name="orders_delete"),
    path("orders/<int:order_id>/newline", OrderLineCreateView.as_view(), name="orderline_new"),
    path("orderline/<int:pk>/update", OrderLineUpdateView.as_view(), name="orderline_update"),
    path("orderline/<int:pk>/delete", OrderLineDeleteView.as_view(), name="orderline_delete"),
]
